name: Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout
      
      - name: Create PDF
        uses: xu-cheng/latex-action@3.2.0
        with:
          root_file: src/recipes.tex
      
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            recipes.pdf