name: Build

permissions:
  contents: write

on:
  push:
    branches: [ "main" ]
    tags: [ "*" ]

jobs:
  build:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create PDF
        uses: addnab/docker-run-action@v3
        with:
          image: miktex/miktex:latest
          options: -v ${{ github.workspace }}:/work -e "TEXINPUTS=/work/src:${TEXINPUTS}:"
          run: pdflatex src/recipes.tex -no-shell-escape
      
      - name: Create release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            recipes.pdf
